
apiVersion: v1
kind: Config
clusters:
- name: kube-auditing
  cluster:
    # use fix ip of webhook service
    server: http://10.96.1.10:8080
contexts:
- context:
    cluster: kube-auditing
    user: ""
  name: default-context
current-context: default-context
preferences: {}
users: []