apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-webhook
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: audit-webhook
      app.kubernetes.io/instance: audit-webhook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: audit-webhook
        app.kubernetes.io/instance: audit-webhook
    spec:
      containers:
      - name: audit-webhook
        image: audit-webhook:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: webhook
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: audit
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: audit-webhook
    app.kubernetes.io/instance: audit-webhook
  # use fix ip!
  clusterIP: 10.96.1.10
  ports:
  - protocol: TCP
    port: 8080
    targetPort: webhook

